language: node_js
node_js:
  - "8"

install:
  - npm install

services:
  - docker

script:
  - npm run lint
  - docker run -p 5432:5432 --name postgres-test-db -e POSTGRES_PASSWORD=root -e POSTGRES_DB=pitches -e POSTGRES_USER=root -d postgres:latest
  - npm test

after_success:
  - docker login $REGISTRY_URL -u $REGISTRY_USER -p $REGISTRY_PASS

  - export APP=sewas/pitchcastjs
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo "staging" ; fi`

  - docker build -t $REGISTRY_URL/$APP:$TAG .
  - docker push $REGISTRY_URL/$APP:$TAG