language: node_js
node_js:
  - "8"

install:
  - npm install

services:
  - docker

script:
  # ENV Vars for Test-DB connection
  - export PITCH_DB_HOST=localhost
  - export PITCH_DB_PITCH_DB_PORT=1234
  - export PITCH_DB_PITCH_DB_USER=root
  - export PITCH_DB_PASSWORD=root
  - export PITCH_DB_NAME=pitches

  - npm run lint
  - docker run -p $PITCH_DB_PORT:5432 --name postgres-test-db -e POSTGRES_PASSWORD=$PITCH_DB_PASSWORD -e POSTGRES_DB=$PITCH_DB_NAME -e POSTGRES_USER=$PITCH_DB_USER -d postgres:latest
  - PITCH_DB_PORT=$PITCH_DB_PORT PITCH_DB_HOST=$PITCH_DB_HOST npm test

after_success:
  - docker login $REGISTRY_URL -u $REGISTRY_USER -p $REGISTRY_PASS

  - export APP=sewas/pitchcastjs
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo "staging" ; fi`

  - docker build -t $REGISTRY_URL/$APP:$TAG .
  - docker push $REGISTRY_URL/$APP:$TAG